baseURL = 'https://MoDELib2.github.io/MoDELib2.github.io/'
languageCode = 'en-us'
title = 'MoDELib2'
theme = "ananke"

[params]
  background = "/images/straight_lines.jpeg"

[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
